[target.'cfg(target_os = "none")']
runner = "arm-none-eabi-gdb -q -x openocd.gdb"

[build]
target = "thumbv7em-none-eabihf"  # Adjust based on your MCU

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-Treset.x",
] 
